version: '3.8'

services:
  vitpose:
    build:
      context: .
      dockerfile: Dockerfile
    image_name: mmaction2-image
    container_name: mmaction2-container
    volumes:
      - ./data:/workspace/data
      - ./models:/workspace/models
      - ./results:/workspace/results
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: all
              capabilities: [gpu]
    restart: unless-stopped
    tty: true
    stdin_open: true
    command: bash